"use strict";
process.env.TZ = process.env.TZ || "America/Mexico_City";
const crypto = require("crypto");
const { Readable } = require("stream");
const { google } = require("googleapis");
const puppeteer = require("puppeteer-extra");
const StealthPlugin = require("puppeteer-extra-plugin-stealth");
puppeteer.use(StealthPlugin());

const env = (n, d="") => String(process.env[n] || d).trim();
const req = n => { const v=env(n); if(!v) throw new Error(`Missing ${n}`); return v; };
const SITE=env("FLOR_SITE_BASE_URL","https://buenainfancia.com.mx").replace(/\/$/,"");
const STRAPI=env("FLOR_STRAPI_BASE_URL","https://strapi.buenainfancia.com.mx").replace(/\/$/,"");
const FOLDER=req("GOOGLE_DRIVE_FOLDER_ID"), SHEET=env("FLOR_WORK_LEDGER_SPREADSHEET_ID","1_pQk5GbdUXBs64xsCLg8s0L6zRORZqi5NpTZV4z1IdA");
const USER=req("FLOR_USERNAME"), PASS=req("FLOR_PASSWORD"), IMP=env("GOOGLE_IMPERSONATED_USER");
const MAX=Math.max(1,parseInt(env("MAX_VIDEOS","1"),10)||1), RS="Resources", LS="Ledger";
const HEADERS=["conference_id","title","resource_key","original_name","source_url","drive_file_id","drive_url","mime_type","size_bytes","status","checked_at","last_error"];
function creds(){const c=JSON.parse(req("GOOGLE_SERVICE_ACCOUNT_JSON"));c.private_key=String(c.private_key).replace(/\\n/g,"\n");return c;}
async function auth(){const c=creds(),a=new google.auth.JWT(c.client_email,null,c.private_key,["https://www.googleapis.com/auth/drive","https://www.googleapis.com/auth/spreadsheets"],IMP||undefined);await a.authorize();return a;}
const q=s=>`'${String(s).replace(/'/g,"''")}'`;
const clean=s=>String(s||"resource").replace(/[\/\\:*?"<>|\x00-\x1f]/g,"").trim()||"resource";
const key=f=>String(f.id??f._id??f.hash??crypto.createHash("sha1").update(String(f.url||f.name)).digest("hex").slice(0,16));
const src=u=>/^https?:\/\//i.test(u)?u:`${STRAPI}${String(u).startsWith("/")?"":"/"}${u}`;
const esc=s=>String(s).replace(/\\/g,"\\\\").replace(/'/g,"\\'");
async function ensure(sheets){const m=await sheets.spreadsheets.get({spreadsheetId:SHEET,fields:"sheets.properties"});if(!(m.data.sheets||[]).some(x=>x.properties?.title===RS))await sheets.spreadsheets.batchUpdate({spreadsheetId:SHEET,requestBody:{requests:[{addSheet:{properties:{title:RS,gridProperties:{rowCount:5000,columnCount:12,frozenRowCount:1}}}}]}});await sheets.spreadsheets.values.update({spreadsheetId:SHEET,range:`${q(RS)}!A1:L1`,valueInputOption:"RAW",requestBody:{values:[HEADERS]}});await sheets.spreadsheets.values.update({spreadsheetId:SHEET,range:`${q(LS)}!L1:P1`,valueInputOption:"RAW",requestBody:{values:[["resources_expected","resources_available","resources_complete","resources_checked_at","resources_last_error"]]}});}
async function login(p){await p.goto(`${SITE}/login`,{waitUntil:"domcontentloaded",timeout:60000});const pw=await p.$("input[type=password]:not([disabled])");if(!pw)return;const ins=await p.$$("input:not([disabled])");let pi=-1;for(let i=0;i<ins.length;i++)if(await ins[i].evaluate(n=>n.type)==="password"){pi=i;break;}const un=pi>0?ins[pi-1]:await p.$("input[type=email],input[name=email],input[type=text]");if(!un)throw new Error("No username field");await un.click({clickCount:3});await un.press("Backspace");await p.keyboard.type(USER);await pw.click({clickCount:3});await pw.press("Backspace");await p.keyboard.type(PASS);const b=await p.$(".btn-morado,button[type=submit],form button");if(!b)throw new Error("No login submit");await Promise.all([b.click(),p.waitForNavigation({waitUntil:"domcontentloaded",timeout:60000}).catch(()=>null)]);}
async function latest(p){await p.goto(`${SITE}/videoconferencias`,{waitUntil:"domcontentloaded",timeout:60000});await p.waitForFunction("window.__NUXT__?.data?.[0]?.videoconferencias",{timeout:30000});const a=await p.evaluate(()=>window.__NUXT__.data[0].videoconferencias);return [...a].reverse().slice(0,MAX);}
async function detail(p,c){await p.goto(`${SITE}/videoconferencias/${c.id}`,{waitUntil:"domcontentloaded",timeout:60000});await p.waitForFunction("window.__NUXT__?.data?.[0]?.videoconferencia",{timeout:30000});const d=await p.evaluate(()=>{const v=window.__NUXT__.data[0].videoconferencia;return{id:v?.id,title:v?.Titulo||v?.titulo||"",files:Array.isArray(v?.files)?v.files.map(f=>({id:f?.id??f?._id,hash:f?.hash,name:f?.name??f?.filename??"",url:f?.url??"",mime:f?.mime??f?.mimeType??""})):null};});if(!Array.isArray(d.files))throw new Error("videoconferencia.files not exposed");return{id:String(d.id??c.id),title:d.title||c.Titulo||c.titulo||"",files:d.files};}
async function find(drive,name){const r=await drive.files.list({q:`'${esc(FOLDER)}' in parents and name='${esc(name)}' and trashed=false`,fields:"files(id,name,mimeType,size,webViewLink)",pageSize:1,supportsAllDrives:true,includeItemsFromAllDrives:true});return r.data.files?.[0]||null;}
async function dl(url,cookie){const r=await fetch(url,{redirect:"follow",headers:{referer:SITE,...(cookie?{cookie}:{})}});if(!r.ok)throw new Error(`HTTP ${r.status}`);const b=Buffer.from(await r.arrayBuffer());if(!b.length)throw new Error("empty resource");return{b,m:(r.headers.get("content-type")||"application/octet-stream").split(";")[0]};}
async function put(drive,d,f,k,cookie){const original=clean(f.name||`resource-${k}`),name=`[${d.id}]_resource_${clean(k).slice(0,32)}_${original}`,url=src(f.url);let x=await find(drive,name);if(!x){const z=await dl(url,cookie);x=(await drive.files.create({supportsAllDrives:true,requestBody:{name,parents:[FOLDER],description:`Flor conference ${d.id} resource: ${original}`,appProperties:{flor_conference_id:d.id,flor_resource_key:k,flor_original_name:original.slice(0,124)}},media:{mimeType:z.m||f.mime||"application/octet-stream",body:Readable.from(z.b)},fields:"id,name,mimeType,size,webViewLink"})).data;}return[original,url,x.id,x.webViewLink||`https://drive.google.com/file/d/${x.id}/view`,x.mimeType||f.mime||"application/octet-stream",Number(x.size||0)];}
async function rows(sheets){return (await sheets.spreadsheets.values.get({spreadsheetId:SHEET,range:`${q(RS)}!A2:L5000`})).data.values||[];}
async function wr(sheets,n,v){const a={spreadsheetId:SHEET,range:n?`${q(RS)}!A${n}:L${n}`:`${q(RS)}!A:L`,valueInputOption:"RAW",requestBody:{values:[v]}};if(n)await sheets.spreadsheets.values.update(a);else await sheets.spreadsheets.values.append({...a,insertDataOption:"INSERT_ROWS"});}
async function ledger(sheets,d,e,a,ok,err=""){const r=await sheets.spreadsheets.values.get({spreadsheetId:SHEET,range:`${q(LS)}!A2:P1000`}),vs=r.data.values||[],i=vs.findIndex(v=>String(v?.[0]||"")===d.id),v=i>=0?Array.from({length:16},(_,j)=>vs[i]?.[j]??""):Array(16).fill("");v[0]=d.id;v[1]=d.title;v[11]=e;v[12]=a;v[13]=ok?"TRUE":"FALSE";v[14]=new Date().toISOString();v[15]=err;if(i>=0)await sheets.spreadsheets.values.update({spreadsheetId:SHEET,range:`${q(LS)}!A${i+2}:P${i+2}`,valueInputOption:"RAW",requestBody:{values:[v]}});else await sheets.spreadsheets.values.append({spreadsheetId:SHEET,range:`${q(LS)}!A:P`,valueInputOption:"RAW",insertDataOption:"INSERT_ROWS",requestBody:{values:[v]}});}
async function sync(p,drive,sheets,c){const d=await detail(p,c),now=new Date().toISOString(),cookie=(await p.cookies()).map(x=>`${x.name}=${x.value}`).join("; "),rs=await rows(sheets),map=new Map(rs.map((v,i)=>[`${v?.[0]}\0${v?.[2]}`,{n:i+2,v}])),seen=new Set(),errs=[];let avail=0;for(const f of d.files){const k=key(f);seen.add(k);const old=map.get(`${d.id}\0${k}`);try{const x=await put(drive,d,f,k,cookie);await wr(sheets,old?.n,[d.id,d.title,k,...x,"available",now,""]);avail++;console.log(`[RESOURCES] ${d.id} available ${x[0]}`);}catch(e){const m=String(e.message||e).slice(0,700);errs.push(`${f.name||k}: ${m}`);await wr(sheets,old?.n,[d.id,d.title,k,clean(f.name||`resource-${k}`),src(f.url),old?.v?.[5]||"",old?.v?.[6]||"",f.mime||old?.v?.[7]||"application/octet-stream",old?.v?.[8]||"","missing",now,m]);}}for(let i=0;i<rs.length;i++){const v=rs[i];if(String(v?.[0]||"")!==d.id)continue;const k=String(v?.[2]||"");if(k&&!seen.has(k)&&String(v?.[9]||"").toLowerCase()!=="removed"){const n=Array.from({length:12},(_,j)=>v?.[j]??"");n[9]="removed";n[10]=now;n[11]="No longer listed by Flor";await wr(sheets,i+2,n);}}const expected=d.files.length,ok=avail===expected&&!errs.length;await ledger(sheets,d,expected,avail,ok,errs.join(" | ").slice(0,1000));console.log(`[RESOURCES] ${d.id} complete=${ok} ${avail}/${expected}`);}
(async()=>{const a=await auth(),drive=google.drive({version:"v3",auth:a}),sheets=google.sheets({version:"v4",auth:a});await ensure(sheets);const b=await puppeteer.launch({headless:env("PUPPETEER_HEADLESS","false").toLowerCase()!=="false",args:["--no-sandbox","--disable-setuid-sandbox"]});try{const p=await b.newPage();await login(p);for(const c of await latest(p))try{await sync(p,drive,sheets,c);}catch(e){const d={id:String(c.id),title:c.Titulo||c.titulo||""};await ledger(sheets,d,"","",false,String(e.message||e).slice(0,1000)).catch(()=>{});console.error(`[RESOURCES][WARN] ${d.id}: ${e.message||e}`);}}finally{await b.close();}})().catch(e=>{console.error(`[RESOURCES][ERROR] ${e.stack||e}`);process.exitCode=1;});
