"use strict";
const { google } = require("googleapis");
const SPREADSHEET=process.env.FLOR_WORK_LEDGER_SPREADSHEET_ID||"1_pQk5GbdUXBs64xsCLg8s0L6zRORZqi5NpTZV4z1IdA";
const OUTBOX=process.env.FLOR_OUTBOX_SHEET||"Outbox", LEDGER=process.env.FLOR_LEDGER_SHEET||"Ledger", RESOURCES=process.env.FLOR_RESOURCES_SHEET||"Resources";
const SA=process.env.GOOGLE_SERVICE_ACCOUNT_JSON||"", IMP=process.env.GOOGLE_IMPERSONATED_USER||"", TARGET=String(process.env.FLOR_OUTBOX_ID||"").trim();
const FORCE=String(process.env.FLOR_FORCE_RESEND||"").toLowerCase()==="true";
const SIG=process.env.FLOR_EMAIL_SIGNATURE_URL||"https://expediente.casitaapps.com/signatures/desarrollo_tecnologico_casitaiedis_edu_mx.jpg?v=1784669030140";
const MAX_BYTES=parseInt(process.env.FLOR_EMAIL_MAX_ATTACHMENTS_BYTES||"18874368",10);
const q=s=>`'${String(s).replace(/'/g,"''")}'`, val=(r,i)=>String(r?.[i]??"").trim();
function authObj(){const c=JSON.parse(SA);c.private_key=String(c.private_key).replace(/\\n/g,"\n");return new google.auth.JWT(c.client_email,null,c.private_key,["https://www.googleapis.com/auth/spreadsheets","https://www.googleapis.com/auth/drive","https://www.googleapis.com/auth/gmail.send","https://www.googleapis.com/auth/gmail.readonly"],IMP);}
const b64=b=>Buffer.from(b).toString("base64").replace(/.{1,76}/g,"$&\r\n").trimEnd();
const b64url=s=>Buffer.from(s,"utf8").toString("base64").replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");
const esc=s=>String(s??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;");
const hdr=s=>`=?UTF-8?B?${Buffer.from(String(s),"utf8").toString("base64")}?=`;
function points(raw){try{const a=JSON.parse(raw);if(Array.isArray(a))return a.map(String).filter(Boolean).slice(0,8);}catch{}return String(raw||"").split(/\r?\n/).map(x=>x.replace(/^[-•*\d.)\s]+/,"").trim()).filter(Boolean).slice(0,8);}
function rowMap(v,n){return{n,outboxId:val(v,0),conferenceId:val(v,1),title:val(v,2),videoUrl:val(v,3),to:val(v,4),cc:val(v,5),subject:val(v,6),summary:val(v,7),keyPoints:val(v,8),status:val(v,9).toLowerCase(),createdAt:val(v,10),claimedAt:val(v,11),sentAt:val(v,12),gmailId:val(v,13),attempts:parseInt(val(v,14)||"0",10)||0,error:val(v,15)};}
function html(r,count){const ps=points(r.keyPoints).map(p=>`<tr><td style="width:18px;vertical-align:top;padding:0 0 12px;color:#1f766f;font-size:18px">•</td><td style="padding:0 0 12px 8px;color:#273545;font-size:15px;line-height:22px">${esc(p)}</td></tr>`).join("");return `<!doctype html><html lang="es"><body style="margin:0;background:#f3f5f7;font-family:Arial,Helvetica,sans-serif;color:#273545"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f3f5f7"><tr><td align="center" style="padding:34px 16px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:660px;background:#fff;border:1px solid #e1e6ea;border-radius:12px;overflow:hidden"><tr><td style="height:6px;background:#1f766f">&nbsp;</td></tr><tr><td style="padding:34px 38px 18px"><h1 style="margin:0;color:#17324d;font-size:27px;line-height:35px">${esc(r.title)}</h1></td></tr><tr><td style="padding:0 38px 8px"><h2 style="margin:0 0 12px;color:#17324d;font-size:16px">Resumen ejecutivo</h2><p style="margin:0;color:#3c4856;font-size:15px;line-height:24px">${esc(r.summary)}</p></td></tr><tr><td style="padding:24px 38px 4px"><h2 style="margin:0 0 16px;color:#17324d;font-size:16px">Puntos clave</h2><table role="presentation" width="100%">${ps}</table></td></tr><tr><td style="padding:18px 38px 12px"><table role="presentation"><tr><td bgcolor="#1f766f" style="border-radius:7px"><a href="${esc(r.videoUrl)}" style="display:inline-block;padding:13px 22px;color:#fff;text-decoration:none;font-size:15px;font-weight:700">Ver conferencia en Google Drive</a></td></tr></table>${count?`<p style="margin:18px 0 0;color:#667381;font-size:13px;line-height:20px">Se adjuntan ${count} recurso${count===1?"":"s"} de la conferencia.</p>`:""}</td></tr><tr><td style="padding:0 38px"><div style="height:1px;background:#e5eaee">&nbsp;</div></td></tr><tr><td style="padding:26px 38px 34px"><img src="cid:flor-signature" alt="Firma de Agustín Alejandro Jurado Jaramillo" width="520" style="display:block;width:100%;max-width:520px;height:auto;border:0"></td></tr></table></td></tr></table></body></html>`;}
function safeName(s){return String(s||"resource").replace(/[\r\n"]/g,"").slice(0,180)||"resource";}
function mime(r,sig,msgid,atts){const mix=`mix_${Date.now()}_${Math.random().toString(16).slice(2)}`,rel=`rel_${Date.now()}_${Math.random().toString(16).slice(2)}`,lines=[`From: ${IMP}`,`To: ${r.to}`,r.cc?`Cc: ${r.cc}`:null,`Subject: ${hdr(r.subject)}`,`Message-ID: <${msgid}>`,`MIME-Version: 1.0`,`Content-Type: multipart/mixed; boundary="${mix}"`,``,`--${mix}`,`Content-Type: multipart/related; boundary="${rel}"`,``,`--${rel}`,`Content-Type: text/html; charset="UTF-8"`,`Content-Transfer-Encoding: base64`,``,b64(Buffer.from(html(r,atts.length),"utf8")),`--${rel}`,`Content-Type: image/jpeg; name="signature.jpg"`,`Content-Transfer-Encoding: base64`,`Content-ID: <flor-signature>`,`Content-Disposition: inline; filename="signature.jpg"`,``,b64(sig),`--${rel}--`];for(const a of atts){const n=safeName(a.name),enc=encodeURIComponent(a.name).replace(/'/g,"%27");lines.push(`--${mix}`,`Content-Type: ${a.mime||"application/octet-stream"}; name="${n}"`,`Content-Transfer-Encoding: base64`,`Content-Disposition: attachment; filename="${n}"; filename*=UTF-8''${enc}`,``,b64(a.bytes));}lines.push(`--${mix}--`,` `);return lines.filter(x=>x!==null).join("\r\n");}
async function updateRow(sheets,n,u){const r=await sheets.spreadsheets.values.get({spreadsheetId:SPREADSHEET,range:`${q(OUTBOX)}!A${n}:P${n}`}),v=Array.from({length:16},(_,i)=>r.data.values?.[0]?.[i]??""),ix={status:9,claimedAt:11,sentAt:12,gmailId:13,attempts:14,error:15};for(const[k,x]of Object.entries(u))v[ix[k]]=x;await sheets.spreadsheets.values.update({spreadsheetId:SPREADSHEET,range:`${q(OUTBOX)}!A${n}:P${n}`,valueInputOption:"RAW",requestBody:{values:[v]}});}
async function ledger(sheets,id){const r=await sheets.spreadsheets.values.get({spreadsheetId:SPREADSHEET,range:`${q(LEDGER)}!A2:P1000`}),vs=r.data.values||[],i=vs.findIndex(v=>val(v,0)===id);return i<0?null:{i,values:vs[i],status:val(vs[i],5).toLowerCase(),gmailId:val(vs[i],6),sentAt:val(vs[i],7),expected:parseInt(val(vs[i],11),10),available:parseInt(val(vs[i],12),10),complete:val(vs[i],13).toUpperCase()==="TRUE"};}
async function markLedger(sheets,r,gid,when){const l=await ledger(sheets,r.conferenceId),v=l?Array.from({length:16},(_,i)=>l.values?.[i]??""):Array(16).fill("");v[0]=r.conferenceId;v[1]=r.title;v[2]="TRUE";v[3]="TRUE";v[5]="sent";v[6]=gid;v[7]=when;v[8]=new Date().toISOString();v[9]="summary_emailed";v[10]="";if(l)await sheets.spreadsheets.values.update({spreadsheetId:SPREADSHEET,range:`${q(LEDGER)}!A${l.i+2}:P${l.i+2}`,valueInputOption:"RAW",requestBody:{values:[v]}});else await sheets.spreadsheets.values.append({spreadsheetId:SPREADSHEET,range:`${q(LEDGER)}!A:P`,valueInputOption:"RAW",insertDataOption:"INSERT_ROWS",requestBody:{values:[v]}});}
async function attachments(sheets,drive,id){const l=await ledger(sheets,id);if(!l||!Number.isInteger(l.expected)||!Number.isInteger(l.available)||!l.complete||l.expected!==l.available)return{ready:false,reason:"Resource inventory incomplete",atts:[]};if(l.expected===0)return{ready:true,atts:[]};const r=await sheets.spreadsheets.values.get({spreadsheetId:SPREADSHEET,range:`${q(RESOURCES)}!A2:L5000`}),rows=(r.data.values||[]).filter(v=>val(v,0)===id&&val(v,9).toLowerCase()==="available"&&val(v,5));const unique=new Map();for(const v of rows)unique.set(val(v,2)||val(v,5),v);if(unique.size!==l.expected)return{ready:false,reason:`Resource rows incomplete ${unique.size}/${l.expected}`,atts:[]};let total=0;const atts=[];for(const v of unique.values()){const fid=val(v,5),name=val(v,3)||`resource-${val(v,2)}`,meta=(await drive.files.get({fileId:fid,fields:"id,name,mimeType,size",supportsAllDrives:true})).data,res=await drive.files.get({fileId:fid,alt:"media",supportsAllDrives:true},{responseType:"arraybuffer"}),bytes=Buffer.from(res.data);total+=bytes.length;if(total>MAX_BYTES)throw new Error(`Resources exceed safe Gmail attachment limit (${total} bytes)`);atts.push({name,mime:meta.mimeType||val(v,7)||"application/octet-stream",bytes});}return{ready:true,atts};}
async function sentBy(gmail,msgid){const r=await gmail.users.messages.list({userId:"me",q:`in:sent rfc822msgid:${msgid}`,maxResults:1});return r.data.messages?.[0]?.id||"";}
function filenames(parts,out=[]){for(const p of parts||[]){if(p.filename)out.push(p.filename);filenames(p.parts,out);}return out;}
(async()=>{const a=authObj();await a.authorize();const sheets=google.sheets({version:"v4",auth:a}),drive=google.drive({version:"v3",auth:a}),gmail=google.gmail({version:"v1",auth:a});const ob=await sheets.spreadsheets.values.get({spreadsheetId:SPREADSHEET,range:`${q(OUTBOX)}!A2:P500`}),rows=(ob.data.values||[]).map((v,i)=>rowMap(v,i+2));let r=TARGET?rows.find(x=>x.outboxId===TARGET):rows.find(x=>["pending","failed","waiting_resources"].includes(x.status));if(!r)throw new Error(`Outbox row not found: ${TARGET||"pending"}`);if(!FORCE&&r.status==="sent"){console.log("[OUTBOX] Already sent");return;}const ar=await attachments(sheets,drive,r.conferenceId);if(!ar.ready){await updateRow(sheets,r.n,{status:"waiting_resources",error:ar.reason});console.log(`[OUTBOX] ${ar.reason}`);return;}const base=`flor-conference-${r.conferenceId}@casitaiedis.edu.mx`.replace(/[^a-zA-Z0-9@._-]/g,"-").toLowerCase(),msgid=FORCE?`flor-conference-${r.conferenceId}-test-${Date.now()}@casitaiedis.edu.mx`:base;if(!FORCE){const x=await sentBy(gmail,msgid),l=await ledger(sheets,r.conferenceId);if(x||l?.status==="sent"||l?.gmailId){const gid=x||l.gmailId,when=l?.sentAt||new Date().toISOString();await updateRow(sheets,r.n,{status:"sent",sentAt:when,gmailId:gid,error:""});console.log("[OUTBOX] Reconciled existing delivery");return;}}await updateRow(sheets,r.n,{status:"sending",claimedAt:new Date().toISOString(),attempts:r.attempts+1,error:""});const sr=await fetch(SIG);if(!sr.ok)throw new Error(`Signature HTTP ${sr.status}`);const sig=Buffer.from(await sr.arrayBuffer()),raw=mime(r,sig,msgid,ar.atts),s=(await gmail.users.messages.send({userId:"me",requestBody:{raw:b64url(raw)}})).data;if(!s.id)throw new Error("Gmail returned no message id");const verify=(await gmail.users.messages.get({userId:"me",id:s.id,format:"full"})).data,names=filenames(verify.payload?.parts);for(const at of ar.atts)if(!names.includes(at.name))throw new Error(`Attachment verification failed: ${at.name}`);const when=new Date().toISOString();await updateRow(sheets,r.n,{status:"sent",sentAt:when,gmailId:s.id,error:""});await markLedger(sheets,r,s.id,when);console.log(`[OUTBOX] Sent ${r.outboxId} attachments=${ar.atts.length} gmail=${s.id}`);})().catch(e=>{console.error(`[OUTBOX][ERROR] ${e.stack||e}`);process.exitCode=1;});
